server:
  port: 8080

spring:
  application:
    name: upi-stack
  
  datasource:
    url: jdbc:h2:mem:upidb
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  
  h2:
    console:
      enabled: true
      path: /h2-console
  
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect
  
  security:
    user:
      name: admin
      password: admin123

logging:
  level:
    com.upi.stack: DEBUG
    org.springframework.security: DEBUG 